name: freebsd

on:
  push:
    paths:
      - '.github/workflows/freebsd.yml'

jobs:
  testfreebsd:
    runs-on: macos-10.15
    name: A job to run test FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Start FreeBSD
      id: test
      uses: vmactions/freebsd-vm@main
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: pkg install -y curl
        sync: rsync
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
    - uses: neilpang/debugger-action@master
    
      
      
      
