name: solaris

on:
  push:
    paths:
      - '.github/workflows/solaris.yml'

jobs:
  testfreebsd:
    runs-on: macos-10.15
    name: A job to run test solaris
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Start solaris
      id: test
      uses: vmactions/solaris-vm@main
      with:
        envs: 'MYTOKEN MYTOKEN2'

        run: |
          pwd
          ls -lah
          whoami
          env
          cat /etc/release
    - name: Sleep
      run: sleep 20
    - uses: neilpang/debugger-action@master
    
      
      
      
